# Generated by Django 2.2.4 on 2019-08-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия автора')),
                ('description', models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Описание автора')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('description', models.CharField(blank=True, default=0, max_length=2000, null=True, verbose_name='Описание книги')),
                ('series', models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Серия')),
                ('image', models.ImageField(upload_to='static/img/')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.Author')),
            ],
        ),
    ]
